name: major-version

on:
  release:
    types: [published, edited]

permissions:
  contents: write

jobs:
  update:
    runs-on: windows-latest

    steps:
      - uses: Actions-R-Us/actions-tagger@v2
